"""add token usage and cost tracking to ai_usage_log

Revision ID: 0eadf51ae5e0
Revises: e8b4a1dc50ee
Create Date: 2026-08-18 16:11:10.533161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eadf51ae5e0'
down_revision: Union[str, Sequence[str], None] = 'e8b4a1dc50ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_usage_log', sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('ai_usage_log', sa.Column('estimated_cost_usd', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_usage_log', 'estimated_cost_usd')
    op.drop_column('ai_usage_log', 'total_tokens')
    # ### end Alembic commands ###
