"""add ai_call_log for per-llm-call structured logging

Revision ID: 433c3dafb52f
Revises: 0eadf51ae5e0
Create Date: 2026-08-18 16:55:59.185423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '433c3dafb52f'
down_revision: Union[str, Sequence[str], None] = '0eadf51ae5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('call_group_id', sa.UUID(), nullable=False),
    sa.Column('call_type', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completion_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), server_default='0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_call_created', 'ai_call_log', ['created_at'], unique=False)
    op.create_index('idx_ai_call_group', 'ai_call_log', ['call_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ai_call_group', table_name='ai_call_log')
    op.drop_index('idx_ai_call_created', table_name='ai_call_log')
    op.drop_table('ai_call_log')
    # ### end Alembic commands ###
