"""add converted_pdf_key to documents

Revision ID: 576b20e69d44
Revises: 338222d0bfcf
Create Date: 2026-08-08 17:40:52.171369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576b20e69d44'
down_revision: Union[str, Sequence[str], None] = '338222d0bfcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('converted_pdf_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'converted_pdf_key')
    # ### end Alembic commands ###
