"""add ai_usage_log for per-user AI quota and observability

Revision ID: e8b4a1dc50ee
Revises: 5e27bd66a382
Create Date: 2026-08-18 13:14:05.391061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8b4a1dc50ee'
down_revision: Union[str, Sequence[str], None] = '5e27bd66a382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('grounded', sa.Boolean(), nullable=True),
    sa.Column('faithfulness_score', sa.Float(), nullable=True),
    sa.Column('retried', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_usage_user_time', 'ai_usage_log', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
    #
    # ĐÃ XOÁ THỦ CÔNG 1 dòng autogenerate sinh ra ở đây:
    #   op.create_index('idx_chunks_embedding', ..., postgresql_using='ivfflat', ...)
    # Alembic thấy DB không còn index này (migration 5e27bd66a382 đã cố ý DROP
    # vì nó trả về 0 dòng cho ~14% truy vấn thật) nhưng model DocumentChunk vẫn
    # còn khai báo → tưởng là thiếu và muốn tạo lại. Đã xoá khai báo trong
    # app/models/chunk.py để autogenerate lần sau không đề xuất lại nữa.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ai_usage_user_time', table_name='ai_usage_log')
    op.drop_table('ai_usage_log')
    # ### end Alembic commands ###
